# Generated by Django 2.1.4 on 2019-04-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('fertilizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fertilizer_freq', models.CharField(max_length=45)),
                ('fertilizer_type', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('flower_id', models.AutoField(primary_key=True, serialize=False)),
                ('flower_type', models.CharField(max_length=45, unique=True)),
                ('flower_date_last', models.DateField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthInstance',
            fields=[
                ('growth_instance_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthType',
            fields=[
                ('growth_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('growth_type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('humidity_id', models.AutoField(primary_key=True, serialize=False)),
                ('humidity_level', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('light_id', models.AutoField(primary_key=True, serialize=False)),
                ('light_type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_date', models.DateField()),
                ('note_name', models.CharField(max_length=45, unique=True)),
                ('note_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=45)),
                ('plant_number', models.CharField(blank=True, default='', max_length=45)),
                ('plant_latin_name', models.CharField(blank=True, default='', max_length=100)),
                ('plant_nickname', models.CharField(blank=True, default='', max_length=45)),
                ('plant_description', models.TextField(blank=True, default='')),
                ('fertilizer', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Fertilizer')),
                ('flower', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Flower')),
                ('humidity', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Humidity')),
                ('light', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Light')),
                ('location', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('soil_id', models.AutoField(primary_key=True, serialize=False)),
                ('soil_type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toxicity',
            fields=[
                ('toxicity_id', models.AutoField(primary_key=True, serialize=False)),
                ('toxicity_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('water_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_freq', models.CharField(max_length=45)),
                ('water_type', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='soil',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Soil'),
        ),
        migrations.AddField(
            model_name='plant',
            name='toxicity',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Toxicity'),
        ),
        migrations.AddField(
            model_name='plant',
            name='water',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plantjournal.Water'),
        ),
        migrations.AddField(
            model_name='note',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='plantjournal.Plant'),
        ),
        migrations.AddField(
            model_name='growthinstance',
            name='growth_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_instances', to='plantjournal.GrowthType'),
        ),
        migrations.AddField(
            model_name='growthinstance',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_instances', to='plantjournal.Plant'),
        ),
    ]
