# Generated by Django 2.1.4 on 2019-04-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantjournal', '0002_auto_20190418_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['flower_type']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.RemoveField(
            model_name='flower',
            name='flower_date_last',
        ),
    ]
