# Generated by Django 2.1.4 on 2019-04-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantjournal', '0004_auto_20190418_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='growthinstance',
            options={'ordering': ['growth_instance_date', 'plant', 'growth_type']},
        ),
        migrations.AlterModelOptions(
            name='growthtype',
            options={'ordering': ['growth_type_name']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['note_date', 'note_name']},
        ),
        migrations.AddField(
            model_name='growthinstance',
            name='growth_instance_date',
            field=models.DateField(default='2018-04-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='growthtype',
            name='growth_type_name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
