# Generated by Django 2.1.4 on 2019-04-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantjournal', '0006_auto_20190418_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('note_date', 'note_name')},
        ),
    ]
