# Generated by Django 2.1.1 on 2018-10-30 17:50

from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


PLANTS = [

    {
        "plant_name": "Screwbean mesquite",
        "latin_name":  "Prosopis pubescens",
    },
    {
        "plant_name": "Kudzu",
        "latin_name":  "Pueraria montana",
    },
    {
        "plant_name": "Wild onion",
        "latin_name":  "Allium canadense",
    },
    {
        "plant_name": "Tree sow thistle",
        "latin_name":  "Sonchus arvensis",
    },
    {
        "plant_name": "Creeping thistle",
        "latin_name":  "Cirsium arvense",
    },
    {
        "plant_name": "Garget",
        "latin_name":  "Phytolacca americana",
    },
    {
        "plant_name": "Perennial thistle",
        "latin_name":  "Cirsium arvense",
    },
    {
        "plant_name": "Indian posy",
        "latin_name":  "Asclepias tuberosa",
    },
    {
        "plant_name": "Clumpfoot cabbage",
        "latin_name":  "Symplocarpus foetidus",
    },
    {
        "plant_name": "Boston fern or sword fern",
        "latin_name":  "Nephrolepis exaltata",
    },
    {
        "plant_name": "Amy root",
        "latin_name":  "Apocynum cannabinum",
    },
    {
        "plant_name": "California walnut",
        "latin_name":  "Juglans californica",
    },
    {
        "plant_name": "Thousand-seal",
        "latin_name":  "Achillea millefolium",
    },
    {
        "plant_name": "Lone fleabane",
        "latin_name":  "Erigeron cavernensis",
    },
    {
        "plant_name": "Pocan bush",
        "latin_name":  "Phytolacca americana",
    },
    {
        "plant_name": "Korean rock fern",
        "latin_name":  "Polystichum tsus-simense",
    },
    {
        "plant_name": "Pigeon berry",
        "latin_name":  "Phytolacca americana",
    },
    {
        "plant_name": "Red ink plant",
        "latin_name":  "Phytolacca americana",
    },
    {
        "plant_name": "Poor Annie",
        "latin_name":  "Veratrum viride",
    },
    {
        "plant_name": "Thousand-leaf",
        "latin_name":  "Achillea millefolium",
    },
    {
        "plant_name": "Pink corydalis",
        "latin_name":  "Corydalis sempervirens",
    },
    {
        "plant_name": "Walnut",
        "latin_name":  "Juglans sp.",
    },
    {
        "plant_name": "Island oak",
        "latin_name":  "Quercus. tomentella",
    },
    {
        "plant_name": "Pleurisy root",
        "latin_name":  "Asclepias tuberosa",
    },
    {
        "plant_name": "Cork oak",
        "latin_name":  "Quercus suber",
    },
    {
        "plant_name": "Shadblow serviceberry",
        "latin_name":  "Amelanchier canadensis",
    },
    {
        "plant_name": "Bird's nest",
        "latin_name":  "Daucus carota",
    },
    {
        "plant_name": "Latanier palm",
        "latin_name":  "Phoenicophorium",
    },
    {
        "plant_name": "Coconut",
        "latin_name":  "Cocos nucifera",
    },
    {
        "plant_name": "Golden chain",
        "latin_name":  "Laburnum",
    },
    {
        "plant_name": "Keek",
        "latin_name":  "Rorippa sylvestris",
    },
    {
        "plant_name": "Wild pellitory",
        "latin_name":  "Achillea ptarmica",
    },
    {
        "plant_name": "Rose milkweed",
        "latin_name":  "Asclepias incarnata",
    },
    {
        "plant_name": "False boxwood",
        "latin_name":  "Cornus florida",
    },
    {
        "plant_name": "Devil's plague",
        "latin_name":  "Daucus carota",
    },
    {
        "plant_name": "Swamp silkweed",
        "latin_name":  "Asclepias incarnata",
    },
    {
        "plant_name": "Blue-of-the-heavens",
        "latin_name":  "Allium caeruleum",
    },
    {
        "plant_name": "Whorled milkweed",
        "latin_name":  "Asclepias verticillata",
    },
    {
        "plant_name": "Cursed thistle",
        "latin_name":  "Cirsium arvense",
    },
    {
        "plant_name": "Skunkweed",
        "latin_name":  "Symplocarpus foetidus",
    },
    {
        "plant_name": "Gordaldo",
        "latin_name":  "Achillea millefolium",
    },
    {
        "plant_name": "Western sword fern",
        "latin_name":  "Polystichum munitum",
    },
    {
        "plant_name": "European weeping birch",
        "latin_name":  "Betula pendula",
    },
    {
        "plant_name": "White trillium",
        "latin_name":  "Trillium grandiflorum",
    },
    {
        "plant_name": "Hogweed",
        "latin_name":  "Ambrosia artemisiifolia",
    },
    {
        "plant_name": "Colic weed",
        "latin_name":  "Corydalis flavula",
    },
    {
        "plant_name": "Judas-tree",
        "latin_name":  "Cercis siliquastrum",
    },
    {
        "plant_name": "Winterberry holly",
        "latin_name":  "Ilex verticillata",
    },
    {
        "plant_name": "Fair-maid-of-France",
        "latin_name":  "Achillea ptarmica",
    },
    {
        "plant_name": "Pine",
        "latin_name":  "Pinus",
    },
    {
        "plant_name": "Silverleaf maple",
        "latin_name":  "Acer saccharinum",
    },
    {
        "plant_name": "Goldenglow",
        "latin_name":  "Rudbeckia laciniata",
    },
    {
        "plant_name": "Purple-flowered Toothwort",
        "latin_name":  "Cardamine concatenata",
    },
    {
        "plant_name": "Shadbush",
        "latin_name":  "Amelanchier canadensis",
    },
    {
        "plant_name": "Woodbine",
        "latin_name":  "Clematis virginiana",
    },
    {
        "plant_name": "Speckled alder",
        "latin_name":  "Alnus incana",
    },
    {
        "plant_name": "African rice",
        "latin_name":  "Oryza glaberrima",
    },
    {
        "plant_name": "Carolina azolla",
        "latin_name":  "Azolla caroliniana",
    },
    {
        "plant_name": "Virginia virgin's bower",
        "latin_name":  "Clematis virginiana",
    },
    {
        "plant_name": "Corn thistle",
        "latin_name":  "Cirsium arvense",
    },
    {
        "plant_name": "Rhubarb",
        "latin_name":  "Rheum rhabarbarum",
    },
    {
        "plant_name": "Cherry birch",
        "latin_name":  "Betula lenta",
    },
    {
        "plant_name": "Earth gall",
        "latin_name":  "Veratrum viride",
    },
    {
        "plant_name": "Angel trumpet",
        "latin_name":  "Brugmansia suaveolens",
    },
    {
        "plant_name": "Common ragwort",
        "latin_name":  "Senecio jacobaea",
    },
    {
        "plant_name": "Soft maple",
        "latin_name":  "Acer saccharinum",
    },
    {
        "plant_name": "Blue ash",
        "latin_name":  "Fraxinus pennsylvanica",
    },
    {
        "plant_name": "Christmas fern",
        "latin_name":  "Polystichum acrostichoides",
    },
    {
        "plant_name": "Native fuchsia",
        "latin_name":  "Epacris longiflora",
    },
    {
        "plant_name": "Durian kura kura",
        "latin_name":  "Durio testudinarum",
    },
    {
        "plant_name": "Garget",
        "latin_name":  "Phytolacca americana",
    },
    {
        "plant_name": "Possumhaw",
        "latin_name":  "Ilex decidua",
    },
    {
        "plant_name": "Judas-tree",
        "latin_name":  "Cercis siliquastrum",
    },
    {
        "plant_name": "Winter rocket",
        "latin_name":  "Barbarea vulgaris",
    },
    {
        "plant_name": "Orange milkweed",
        "latin_name":  "Asclepias tuberosa",
    },
    {
        "plant_name": "English oak",
        "latin_name":  "Quercus robur",
    },
    {
        "plant_name": "Peanut",
        "latin_name":  "Arachis hypogaea",
    },
    {
        "plant_name": "Leopard lily",
        "latin_name":  "Lilium catesbaei",
    },
    {
        "plant_name": "Petty morel",
        "latin_name":  "Solanum nigrum",
    },
    {
        "plant_name": "Gray alder",
        "latin_name":  "Alnus incana",
    },
    {
        "plant_name": "Vanilla orchid",
        "latin_name":  "Vanilla",
    },
    {
        "plant_name": "Coyote willow",
        "latin_name":  "Salix exigua",
    },
    {
        "plant_name": "Hare's thistle",
        "latin_name":  "Sonchus oleraceus",
    },
    {
        "plant_name": "Swinies",
        "latin_name":  "Sonchus oleraceus",
    },
    {
        "plant_name": "Potato",
        "latin_name":  "Solanum tuberosum",
    },
    {
        "plant_name": "Winter gilliflower",
        "latin_name":  "Hesperis matronalis",
    },
    {
        "plant_name": "Scurvy cress",
        "latin_name":  "Barbarea verna",
    },
    {
        "plant_name": "Brittlebush",
        "latin_name":  "Encelia farinosa",
    },
    {
        "plant_name": "Moose maple",
        "latin_name":  "Acer pensylvanicum",
    },
    {
        "plant_name": "Golden buttons",
        "latin_name":  "Tanacetum vulgare",
    },
    {
        "plant_name": "Yellow birch",
        "latin_name":  "Betula alleghaniensis",
    },
    {
        "plant_name": "Skunkweed",
        "latin_name":  "Symplocarpus foetidus",
    },
    {
        "plant_name": "Sugarplum",
        "latin_name":  "Amelanchier canadensis",
    },
    {
        "plant_name": "Valley oak",
        "latin_name":  "Quercus lobata",
    },
    {
        "plant_name": "Wayside plantain",
        "latin_name":  "Plantago major",
    },
    {
        "plant_name": "Possumhaw",
        "latin_name":  "Ilex decidua",
    },
    {
        "plant_name": "Poisonberry",
        "latin_name":  "Solanum dulcamara",
    },
    {
        "plant_name": "California thistle",
        "latin_name":  "Cirsium arvense",
    },
    {
        "plant_name": "Clover",
        "latin_name":  "Trifolium spp.",
    },
    {
        "plant_name": "Elephant apple",
        "latin_name":  "Dillenia indica",
    },
    {
        "plant_name": "Yunnan camellia",
        "latin_name":  "Camellia yunnanensis",
    },
    {
        "plant_name": "Earth gall",
        "latin_name":  "Veratrum viride",
    },
    {
        "plant_name": "Poppy",
        "latin_name":  "Papaveraceae",
    },
    {
        "plant_name": "Maize",
        "latin_name":  "Zea mays",
    },
    {
        "plant_name": "Shadbush",
        "latin_name":  "Amelanchier canadensis",
    },
    {
        "plant_name": "Viper's grass",
        "latin_name":  "Scorzonera hispanica",
    },
    {
        "plant_name": "Pocan bush",
        "latin_name":  "Phytolacca americana",
    },
    {
        "plant_name": "Sycamore (Arizona)",
        "latin_name":  "Platanus wrighitii",
    },
    {
        "plant_name": "Rye",
        "latin_name":  "Secale cereale",
    },
    {
        "plant_name": "Juneberry",
        "latin_name":  "Amelanchier canadensis",
    },
    {
        "plant_name": "California walnut",
        "latin_name":  "Juglans californica",
    },
    {
        "plant_name": "Swamp milkweed",
        "latin_name":  "Asclepias incarnata",
    },
    {
        "plant_name": "Roadweed",
        "latin_name":  "Plantago major",
    },
    {
        "plant_name": "Lily of the Nile",
        "latin_name":  "Agapanthus praecox",
    },
    {
        "plant_name": "Potato",
        "latin_name":  "Solanum tuberosum",
    },
    {
        "plant_name": "Night scented gilliflower",
        "latin_name":  "Hesperis matronalis",
    },
    {
        "plant_name": "Meadow holly",
        "latin_name":  "Ilex decidua",
    },
    {
        "plant_name": "Greater plantain",
        "latin_name":  "Plantago major",
    },
    {
        "plant_name": "Sneezewort yarrow",
        "latin_name":  "Achillea ptarmica",
    },
    {
        "plant_name": "Jack-by-the-hedge",
        "latin_name":  "Alliaria petiolata",
    },
    {
        "plant_name": "Haldi",
        "latin_name":  "Curcuma domestica",
    },
    {
        "plant_name": "Jugflower",
        "latin_name":  "Adenanthos obovatus",
    },
    {
        "plant_name": "Devil's bite",
        "latin_name":  "Veratrum viride",
    },
    {
        "plant_name": "Traveller's joy",
        "latin_name":  "Clematis virginiana",
    },
    {
        "plant_name": "Eastern coneflower",
        "latin_name":  "Rudbeckia fulgida",
    },
    {
        "plant_name": "Saskatoon",
        "latin_name":  "Amelanchier alnifolia",
    },
    {
        "plant_name": "Sword ferns",
        "latin_name":  "Polystichum spp.",
    },
    {
        "plant_name": "Trailing nightshade",
        "latin_name":  "Solanum dulcamara",
    },
    {
        "plant_name": "White mulberry",
        "latin_name":  "Morus alba",
    },
    {
        "plant_name": "Green ash",
        "latin_name":  "Fraxinus pennsylvanica",
    },
    {
        "plant_name": "Scurvy cress",
        "latin_name":  "Barbarea verna",
    },
    {
        "plant_name": "Scoke",
        "latin_name":  "Phytolacca americana",
    },
    {
        "plant_name": "Gloriosa daisy",
        "latin_name":  "Rudbeckia hirta",
    },
    {
        "plant_name": "Peach",
        "latin_name":  "Prunus persica",
    },
    {
        "plant_name": "Lily leek",
        "latin_name":  "Allium moly",
    },
    {
        "plant_name": "Sand brier",
        "latin_name":  "Solanum carolinense",
    },
    {
        "plant_name": "Carrot weed",
        "latin_name":  "Ambrosia artemisiifolia",
    },
    {
        "plant_name": "Zedoary",
        "latin_name":  "Curcuma zedoaria",
    },
    {
        "plant_name": "Creek maple",
        "latin_name":  "Acer saccharinum",
    },

]


def add_plant_data(apps, schema_editor):
    plant_class = apps.get_model('plantjournal', 'Plant')
    for plant in PLANTS:
        try:
            duplicate_object = plant_class.objects.get(
                plant_name=plant['plant_name'],
                plant_latin_name=plant['latin_name']
            )
            print('Duplicate plant entry not added to plant table:', plant['plant_name'], plant['latin_name'])
        except ObjectDoesNotExist:
            plant_object = plant_class.objects.create(
                plant_name=plant['plant_name'],
                plant_latin_name=plant['latin_name']
            )


def remove_plant_data(apps, schema_editor):
    plant_class = apps.get_model('plantjournal', 'Plant')
    for plant in PLANTS:
        try:
            plant_object = plant_class.objects.get(
                plant_name=plant['plant_name'],
                plant_latin_name=plant['latin_name']

            )
            plant_object.delete()
        except ObjectDoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('plantjournal', '0008_auto_20190501_1826'),
    ]

    operations = [
        migrations.RunPython(
            add_plant_data,
            remove_plant_data
        )
    ]
