# Generated by Django 2.1.4 on 2019-05-03 00:43

from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


NOTES = [

    {
        "note_date": "2000-01-01",
        "note_name":  "Test Note 1",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2001-01-01",
        "note_name":  "Test Note 2",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2002-01-01",
        "note_name":  "Test Note 3",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2003-01-01",
        "note_name":  "Test Note 4",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2004-01-01",
        "note_name":  "Test Note 5",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2005-01-01",
        "note_name":  "Test Note 6",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2006-01-01",
        "note_name":  "Test Note 7",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2007-01-01",
        "note_name":  "Test Note 8",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2008-01-01",
        "note_name":  "Test Note 9",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2009-01-01",
        "note_name":  "Test Note 10",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2010-01-01",
        "note_name":  "Test Note 11",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2011-01-01",
        "note_name":  "Test Note 12",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2012-01-01",
        "note_name":  "Test Note 13",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2013-01-01",
        "note_name":  "Test Note 14",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2014-01-01",
        "note_name":  "Test Note 15",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2015-01-01",
        "note_name":  "Test Note 16",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2016-01-01",
        "note_name":  "Test Note 17",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2017-01-01",
        "note_name":  "Test Note 18",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2018-01-01",
        "note_name":  "Test Note 19",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2019-01-01",
        "note_name":  "Test Note 20",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2020-01-01",
        "note_name":  "Test Note 21",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2021-01-01",
        "note_name":  "Test Note 22",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2022-01-01",
        "note_name":  "Test Note 23",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2023-01-01",
        "note_name":  "Test Note 24",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2024-01-01",
        "note_name":  "Test Note 25",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2025-01-01",
        "note_name":  "Test Note 26",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2026-01-01",
        "note_name":  "Test Note 27",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2027-01-01",
        "note_name":  "Test Note 28",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2028-01-01",
        "note_name":  "Test Note 29",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2029-01-01",
        "note_name":  "Test Note 30",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2030-01-01",
        "note_name":  "Test Note 31",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2031-01-01",
        "note_name":  "Test Note 32",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2032-01-01",
        "note_name":  "Test Note 33",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2033-01-01",
        "note_name":  "Test Note 34",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2034-01-01",
        "note_name":  "Test Note 35",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2035-01-01",
        "note_name":  "Test Note 36",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2036-01-01",
        "note_name":  "Test Note 37",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2037-01-01",
        "note_name":  "Test Note 38",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2038-01-01",
        "note_name":  "Test Note 39",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2039-01-01",
        "note_name":  "Test Note 40",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2040-01-01",
        "note_name":  "Test Note 41",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2041-01-01",
        "note_name":  "Test Note 42",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2042-01-01",
        "note_name":  "Test Note 43",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2043-01-01",
        "note_name":  "Test Note 44",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2044-01-01",
        "note_name":  "Test Note 45",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2045-01-01",
        "note_name":  "Test Note 46",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2046-01-01",
        "note_name":  "Test Note 47",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2047-01-01",
        "note_name":  "Test Note 48",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2048-01-01",
        "note_name":  "Test Note 49",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2049-01-01",
        "note_name":  "Test Note 50",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2050-01-01",
        "note_name":  "Test Note 51",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2051-01-01",
        "note_name":  "Test Note 52",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2052-01-01",
        "note_name":  "Test Note 53",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2053-01-01",
        "note_name":  "Test Note 54",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2054-01-01",
        "note_name":  "Test Note 55",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2055-01-01",
        "note_name":  "Test Note 56",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2056-01-01",
        "note_name":  "Test Note 57",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2057-01-01",
        "note_name":  "Test Note 58",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2058-01-01",
        "note_name":  "Test Note 59",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2059-01-01",
        "note_name":  "Test Note 60",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2060-01-01",
        "note_name":  "Test Note 61",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2061-01-01",
        "note_name":  "Test Note 62",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2062-01-01",
        "note_name":  "Test Note 63",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2063-01-01",
        "note_name":  "Test Note 64",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2064-01-01",
        "note_name":  "Test Note 65",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2065-01-01",
        "note_name":  "Test Note 66",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2066-01-01",
        "note_name":  "Test Note 67",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2067-01-01",
        "note_name":  "Test Note 68",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2068-01-01",
        "note_name":  "Test Note 69",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2069-01-01",
        "note_name":  "Test Note 70",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2070-01-01",
        "note_name":  "Test Note 71",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2071-01-01",
        "note_name":  "Test Note 72",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2072-01-01",
        "note_name":  "Test Note 73",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2073-01-01",
        "note_name":  "Test Note 74",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2074-01-01",
        "note_name":  "Test Note 75",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2075-01-01",
        "note_name":  "Test Note 76",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2076-01-01",
        "note_name":  "Test Note 77",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2077-01-01",
        "note_name":  "Test Note 78",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2078-01-01",
        "note_name":  "Test Note 79",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2079-01-01",
        "note_name":  "Test Note 80",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2080-01-01",
        "note_name":  "Test Note 81",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2081-01-01",
        "note_name":  "Test Note 82",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2082-01-01",
        "note_name":  "Test Note 83",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2083-01-01",
        "note_name":  "Test Note 84",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2084-01-01",
        "note_name":  "Test Note 85",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2085-01-01",
        "note_name":  "Test Note 86",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2086-01-01",
        "note_name":  "Test Note 87",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2087-01-01",
        "note_name":  "Test Note 88",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2088-01-01",
        "note_name":  "Test Note 89",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2089-01-01",
        "note_name":  "Test Note 90",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2090-01-01",
        "note_name":  "Test Note 91",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2091-01-01",
        "note_name":  "Test Note 92",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2092-01-01",
        "note_name":  "Test Note 93",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2093-01-01",
        "note_name":  "Test Note 94",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2094-01-01",
        "note_name":  "Test Note 95",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2095-01-01",
        "note_name":  "Test Note 96",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2096-01-01",
        "note_name":  "Test Note 97",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2097-01-01",
        "note_name":  "Test Note 98",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2098-01-01",
        "note_name":  "Test Note 99",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2099-01-01",
        "note_name":  "Test Note 100",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2100-01-01",
        "note_name":  "Test Note 101",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2101-01-01",
        "note_name":  "Test Note 102",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2102-01-01",
        "note_name":  "Test Note 103",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2103-01-01",
        "note_name":  "Test Note 104",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2104-01-01",
        "note_name":  "Test Note 105",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2105-01-01",
        "note_name":  "Test Note 106",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2106-01-01",
        "note_name":  "Test Note 107",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2107-01-01",
        "note_name":  "Test Note 108",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2108-01-01",
        "note_name":  "Test Note 109",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2109-01-01",
        "note_name":  "Test Note 110",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2110-01-01",
        "note_name":  "Test Note 111",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2111-01-01",
        "note_name":  "Test Note 112",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2112-01-01",
        "note_name":  "Test Note 113",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2113-01-01",
        "note_name":  "Test Note 114",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2114-01-01",
        "note_name":  "Test Note 115",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2115-01-01",
        "note_name":  "Test Note 116",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2116-01-01",
        "note_name":  "Test Note 117",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2117-01-01",
        "note_name":  "Test Note 118",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2118-01-01",
        "note_name":  "Test Note 119",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2119-01-01",
        "note_name":  "Test Note 120",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2120-01-01",
        "note_name":  "Test Note 121",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2121-01-01",
        "note_name":  "Test Note 122",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2122-01-01",
        "note_name":  "Test Note 123",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2123-01-01",
        "note_name":  "Test Note 124",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2124-01-01",
        "note_name":  "Test Note 125",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2125-01-01",
        "note_name":  "Test Note 126",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2126-01-01",
        "note_name":  "Test Note 127",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2127-01-01",
        "note_name":  "Test Note 128",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2128-01-01",
        "note_name":  "Test Note 129",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2129-01-01",
        "note_name":  "Test Note 130",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2130-01-01",
        "note_name":  "Test Note 131",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2131-01-01",
        "note_name":  "Test Note 132",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2132-01-01",
        "note_name":  "Test Note 133",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2133-01-01",
        "note_name":  "Test Note 134",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2134-01-01",
        "note_name":  "Test Note 135",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2135-01-01",
        "note_name":  "Test Note 136",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2136-01-01",
        "note_name":  "Test Note 137",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2137-01-01",
        "note_name":  "Test Note 138",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2138-01-01",
        "note_name":  "Test Note 139",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2139-01-01",
        "note_name":  "Test Note 140",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2140-01-01",
        "note_name":  "Test Note 141",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2141-01-01",
        "note_name":  "Test Note 142",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2142-01-01",
        "note_name":  "Test Note 143",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2143-01-01",
        "note_name":  "Test Note 144",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2144-01-01",
        "note_name":  "Test Note 145",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2145-01-01",
        "note_name":  "Test Note 146",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2146-01-01",
        "note_name":  "Test Note 147",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2147-01-01",
        "note_name":  "Test Note 148",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2148-01-01",
        "note_name":  "Test Note 149",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },
    {
        "note_date": "2149-01-01",
        "note_name":  "Test Note 150",
        "note_body": "test data",
        "plant":  "Bird of Paradise",
    },

]


def add_note_data(apps, schema_editor):
    note_class = apps.get_model('plantjournal', 'Note')
    plant_class = apps.get_model('plantjournal', 'Plant')
    plant_object = plant_class.objects.get(plant_name='Bird of Paradise')
    for note in NOTES:
        note_object = note_class.objects.create(
            note_date=note['note_date'],
            note_name=note['note_name'],
            note_body=note['note_body'],
            plant=plant_object
        )


def remove_note_data(apps, schema_editor):
    note_class = apps.get_model('plantjournal', 'Note')
    plant_class = apps.get_model('plantjournal', 'Plant')
    plant_object = plant_class.objects.get(plant_name='Bird of Paradise')
    for note in NOTES:
        try:
            note_object = note_class.objects.get(
                note_date=note['note_date'],
                note_name=note['note_name'],
                note_body=note['note_body'],
                plant=plant_object
            )
            note_object.delete()
        except ObjectDoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('plantjournal', '0009_load_plant_test_data'),
    ]

    operations = [
        migrations.RunPython(
            add_note_data,
            remove_note_data
        )
    ]
