# Generated by Django 2.1.4 on 2019-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantjournal', '0010_load_note_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthinstance',
            name='growth_instance_date',
            field=models.DateField(default='00/00/0000'),
        ),
    ]
